apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-system-deployment
  labels:
    app: bank-system

spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-system

  template:
    metadata:
      labels:
        app: bank-system
    spec:
      containers:
      - name: bank-system-ctr
        image: anubislord2109/bank-system:latest
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
