apiVersion: v1
kind: Service
metadata:
  name: bank-system-svc

spec:
  selector:
    app: bank-system

  ports:
    - protocol: TCP
      port: 30002
      targetPort: 5000
      nodePort: 30002
  type: NodePort
